services:
  # 1. Flask 웹 서비스
  - type: web
    name: deepshield-web
    env: python
    plan: starter
    buildCommand: pip install -r apps/webapp/requirements.txt
    startCommand: gunicorn app:app
    workingDirectory: apps/webapp

  # 2. 워터마크 API (FastAPI) 서비스
  - type: web
    name: deepshield-api
    env: python
    plan: starter
    buildCommand: pip install -r apps/mate/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 5002
    workingDirectory: apps/mate
