"""add social auth columns to user

Revision ID: 502e67ce3917
Revises: dea78ea5f1c8
Create Date: 2025-10-20 18:15:55.633775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502e67ce3917'
down_revision = 'dea78ea5f1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=512), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_provider_id'), ['provider_id'], unique=False)
        batch_op.create_unique_constraint('uq_provider_pid', ['provider', 'provider_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_pid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_provider_id'))
        batch_op.drop_index(batch_op.f('ix_user_provider'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('picture')
        batch_op.drop_column('name')
        batch_op.drop_column('email')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
